# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer



from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, StringVar, filedialog

from config import AppConfig
from logger import logger
from updater_service import UpdaterService

app_config = AppConfig()
updater_service = UpdaterService()

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame0")



def browse_folder(ev: StringVar):
    folder_path = filedialog.askdirectory()
    ev.set(folder_path)
    app_config.set_setting("WOW_ADDONS_FOLDER", folder_path)


def process_folder(ev: StringVar):
    folder_path = ev.get()
    # Add your code to process the folder_path as needed
    logger.info(f"Processing folder: {folder_path}")
    updater_service.update_elvui(folder_path)


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title("Elvui updater")
wow_addons_folder = app_config.get_setting("WOW_ADDONS_FOLDER")

if not wow_addons_folder:
    logger.warning("Please save a folder for wow addons")

window.geometry("994x356")
window.configure(bg="#071022")

canvas = Canvas(
    window,
    bg="#071022",
    height=356,
    width=994,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
canvas.create_rectangle(
    469.0,
    0.0,
    1012.0,
    506.0,
    fill="#FFFFFF",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    730.7667999267578,
    178.237154006958,
    image=entry_image_1
)
entry_var = StringVar(value=wow_addons_folder)
entry_1 = Entry(
    bd=0,
    bg="#EFEFEF",
    fg="#000716",
    highlightthickness=0,
    state="disabled",
    textvariable=entry_var
)
entry_1.place(
    x=512.0,
    y=161.0,
    width=437.5335998535156,
    height=32.474308013916016
)

canvas.create_text(
    511.0,
    93.0,
    anchor="nw",
    text="Select the folder",
    fill="#5E95FF",
    font=("Montserrat Bold", 32 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: browse_folder(entry_var),
    relief="flat"
)
button_1.place(
    x=504.0,
    y=249.0,
    width=190.0,
    height=48.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: process_folder(entry_var),
    relief="flat"
)
button_2.place(
    x=775.0,
    y=248.0,
    width=190.0,
    height=48.0
)

canvas.create_text(
    45.0,
    45.0,
    anchor="nw",
    text="Elvui Updater",
    fill="#FFFFFF",
    font=("Montserrat Bold", 50 * -1)
)
canvas.create_text(
    51.0,
    138.0,
    anchor="nw",
    text="Are you tired of updating Elvui ",
    fill="#FFFFFF",
    font=("Montserrat Regular", 18 * -1)
)

canvas.create_text(
    51.0,
    173.0,
    anchor="nw",
    text="manually. Select your World of ",
    fill="#FFFFFF",
    font=("Montserrat Regular", 18 * -1)
)

canvas.create_text(
    51.0,
    212.0,
    anchor="nw",
    text="Warcraft addons folder and click ",
    fill="#FFFFFF",
    font=("Montserrat Regular", 18 * -1)
)

canvas.create_text(
    51.0,
    244.0,
    anchor="nw",
    text="update",
    fill="#FFFFFF",
    font=("Montserrat Regular", 18 * -1)
)

canvas.create_text(
    45.0,
    311.0,
    anchor="nw",
    text="© Molg, 2023",
    fill="#FFFFFF",
    font=("Montserrat Bold", 18 * -1)
)
window.resizable(False, False)
window.mainloop()
